AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: In the Hood webhook endpoint

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      CodeUri: ./
      Description: Receives webhook events for In the Hood
      Environment:
        Variables:
          WEBHOOK_SECRET: ''
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  WebhookUrl:
    Description: API Gateway endpoint URL for the webhook
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'
