// This file is typically generated by the Amplify CLI.
// Replace the placeholder string with your real Amplify configuration.
const amplifyconfig = r'''
{
  "UserAgent": "aws-amplify/cli",
  "Version": "1.0"
}
''';
