// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--8-lOrn1wJxop_rbUFUzRIE2MD2kiJU',
    appId: '1:662735859640:web:1612497b38b32bea0ce94d',
    messagingSenderId: '662735859640',
    projectId: 'in-the-hood',
    authDomain: 'in-the-hood.firebaseapp.com',
    storageBucket: 'in-the-hood.appspot.com',
    measurementId: 'G-3NMY4SX7V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXbamKsZVPiVQvlco1NIikRIVGQx4Un5I',
    appId: '1:662735859640:android:ef1b0c8d349ff9050ce94d',
    messagingSenderId: '662735859640',
    projectId: 'in-the-hood',
    storageBucket: 'in-the-hood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANL-oF4VIQLM__FOIR_cj33kNQza5yIDA',
    appId: '1:662735859640:ios:9804e47c83a2ddac0ce94d',
    messagingSenderId: '662735859640',
    projectId: 'in-the-hood',
    storageBucket: 'in-the-hood.appspot.com',
    iosBundleId: 'com.example.inTheHood',
  );

    static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANL-oF4VIQLM__FOIR_cj33kNQza5yIDA',
    appId: '1:662735859640:ios:9804e47c83a2ddac0ce94d',
    messagingSenderId: '662735859640',
    projectId: 'in-the-hood',
    storageBucket: 'in-the-hood.appspot.com',
    iosBundleId: 'com.example.inTheHood',
  );
}
